name: Simple manual workflow

on:
  push:
    branches:
      - main
      - dev
      - test
jobs:

  DEV:
    runs-on: ubuntu-latest
    environment: DEV

    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v2
  
      - name: Run a script
        run: |
          echo "I am running in dev env"

          
  QA:
    runs-on: ubuntu-latest
    environment: QA

    if: github.ref == 'refs/heads/test'
    steps:
      - uses: actions/checkout@v2

      - name: Run a script
        run: |
          echo "I am running in QA env"
      
      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Requirements
        run: |
          pip install -r backend/requirements.txt

      - name: Run test scripts
        run: |
          python -m unittest discover -s backend/tests
     
  PROD:
    runs-on: ubuntu-latest
    environment: PROD

    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Run a script
        run: |
          echo "I am runnig in PROD env"
