name: Simple manual workflow

on:
  push:
    branches:
      - main

jobs:

  DEV:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - uses: actions/checkout@v2
  
      - name: Run a script
        run: |
          echo "I am running in dev env"


  QA:
    runs-on: ubuntu-latest
    environment: QA
    needs: DEV

    steps:
      - uses: actions/checkout@v2

      - name: Run a script
        run: |
          echo "I am running in QA env"


  PROD:
    runs-on: ubuntu-latest
    environment: PROD
    needs: QA

    steps:
      - uses: actions/checkout@v2
      - name: Run a script
        run: |
          echo "I am runnig in PROD env"










    
  
